id: P004176
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181177
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། བྱང་གཏེར་བཀའ་བརྒྱད་ཀྱི་སྐོར།
  author: ''
  volumes:
    47c256bec6dc4703801daa1b118c801e:
      image_group_id: I1KG16349
      title: ''
      volume_number: 1
      total_pages: 1226
